import type { TranscriptLine } from './store'

export const SAMPLE_TRANSCRIPT: TranscriptLine[] = [
  { text: "Good morning, everyone. Thank you for joining us today." },
  { text: "We're here to explore one of the most transformative topics of our time: artificial intelligence in healthcare." },
  { text: "Let me start with a simple question — what does a doctor do that a machine cannot?" },
  { text: "The answer, until recently, was almost everything. Diagnosis, empathy, judgment, experience." },
  { text: "But the landscape is shifting dramatically, and I want to walk you through exactly how." },
  { text: "First, let's talk about diagnostic imaging. AI models trained on millions of X-rays can now detect early-stage lung cancer with greater accuracy than the average radiologist." },
  { text: "This isn't science fiction. This is happening in hospitals across the Netherlands, the UK, and the United States right now." },
  { text: "The key technology here is called a convolutional neural network — a type of deep learning model that learns to recognize visual patterns in medical scans." },
  { text: "What's remarkable is the speed. Where a radiologist might take 20 minutes to analyze a chest CT, the model completes the same analysis in under 3 seconds." },
  { text: "But speed alone isn't the point. The real value is catching things human eyes miss — subtle nodules, early lesions, density changes invisible to the untrained eye." },
  { text: "Now let's move to a different domain: drug discovery." },
  { text: "Developing a new drug traditionally takes 10 to 15 years and costs upward of 2 billion euros." },
  { text: "AI is compressing that timeline by predicting how molecules will interact with specific proteins in the body." },
  { text: "DeepMind's AlphaFold solved a 50-year-old problem in structural biology by predicting protein folding with near-perfect accuracy." },
  { text: "This has opened the door to designing targeted therapies for diseases that were previously considered undruggable." },
  { text: "The implications for cancer, Alzheimer's, and rare genetic disorders are enormous." },
  { text: "Let me shift now to something closer to daily patient care: clinical decision support." },
  { text: "These are AI systems embedded in electronic health records that alert physicians to potential drug interactions, sepsis risk, or deteriorating vital signs." },
  { text: "One system deployed at a major hospital in Amsterdam reduced sepsis mortality by 18% simply by flagging at-risk patients 6 hours earlier than nurses typically would." },
  { text: "Six hours. In sepsis, that's the difference between recovery and organ failure." },
  { text: "Now, I want to address the concern that's on many of your minds: will AI replace doctors?" },
  { text: "The honest answer is: not entirely, and not anytime soon — but it will fundamentally change what doctors spend their time doing." },
  { text: "Routine pattern recognition, documentation, triage scoring — these will increasingly be handled by AI." },
  { text: "What remains irreplaceable is the human relationship: the conversation in a difficult diagnosis, the judgment call when guidelines don't fit the patient in front of you." },
  { text: "Think of AI as giving every doctor a brilliant, tireless research assistant who never forgets a study, never misses a data point, and never burns out." },
  { text: "But that assistant still needs a physician to decide what to do with the information." },
  { text: "There are also critical challenges we must confront honestly." },
  { text: "Algorithmic bias is real. If a model is trained predominantly on data from white male patients, it may underperform for women or non-European populations." },
  { text: "Data privacy raises serious ethical questions — your medical history is among the most sensitive information that exists." },
  { text: "And explainability matters. A model that says 'this patient has a 74% chance of readmission' is only useful if the physician understands why." },
  { text: "Regulation is catching up. The EU AI Act now classifies medical AI as high-risk, demanding transparency, human oversight, and rigorous clinical validation." },
  { text: "This is the right direction. We need AI in healthcare to be trustworthy, not just powerful." },
  { text: "So what does the next decade look like?" },
  { text: "I believe we will see AI-native hospitals within 10 years — where every clinical decision is informed by real-time data, predictive models, and personalized patient histories." },
  { text: "The doctors of tomorrow will be trained not just in anatomy and pharmacology, but in data literacy and human-AI collaboration." },
  { text: "The goal is not to remove the human from healthcare. The goal is to make every human in healthcare dramatically more capable." },
  { text: "Thank you. I'm happy to take your questions." },
]
